# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath:static/db/schema-h2.sql
      data-locations: classpath:static/db/data-h2.sql